apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubeapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kubeapp
  template:
    metadata:
      labels:
        app: kubeapp
    spec:
      containers:
      - name: kubeapp
        image: priyamvadaae4/kubeapp:latest
        ports:
        - containerPort: 80
